import assert from 'node:assert/strict';
import { alignedPieces, angleDistance, catchOrbit, newFlight, stepFlight } from '../public/game-rules.mjs';
assert.equal(alignedPieces([4, 8, 12]), 3);
assert.equal(alignedPieces([1, 0, 3]), 1);
assert.ok(angleDistance(.05, Math.PI * 2 - .05) < .101);
assert.equal(catchOrbit({ hits: 4, misses: 0 }, .04, 0).done, true);
assert.equal(catchOrbit({ hits: 0, misses: 2 }, 2, 0).done, true);
const hit = newFlight();
Object.assign(hit, { hits: 11, fireIn: 1, spawnIn: 1, bullets: [{ x: 160, y: 100 }], enemies: [{ x: 160, y: 100 }] });
stepFlight(hit, .01, 160, 20);
assert.equal(hit.hits, 12); assert.equal(hit.done, true); assert.equal(hit.enemies.length, 0);
stepFlight(hit, .05, 0, 20); assert.equal(hit.x, 160);
const miss = newFlight();
Object.assign(miss, { misses: 2, enemies: [{ x: 30, y: 260 }] });
stepFlight(miss, .01, 160, 20);
assert.equal(miss.misses, 3); assert.equal(miss.done, true);
const flight = newFlight();
for (let i = 0; i < 3000 && !flight.done; i++) stepFlight(flight, 1 / 60, 160, 160);
assert.equal(flight.hits, 12); assert.equal(flight.misses, 0); assert.equal(flight.done, true);
const bounds = newFlight(); bounds.x = 16; stepFlight(bounds, .05, -100, 25); assert.equal(bounds.x, 16);
console.log('Assembly alignment, Orbit wraparound/win/loss, Flight collisions/win/loss/bounds passed.');
